FROM node:16.15.1

# Buat Nodejs App Direktori pada Container
WORKDIR /home/app/

# copy semua file package.json ke dalam Direktori Nodejs App di container
COPY package*.json ./

RUN npm install
# jalankan perintah npm install untuk menginstall dependensi yang diperlukan 

# Bundle app source
COPY . .

EXPOSE 3001
CMD [ "node", "app.js" ]
